### ISSUE TITLE
Опечатки в коде

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#11]
Чтобы не допускать опечаток, установи специальное расширение. Для VS Code есть Code Spell Checker.
![Выделение_030](https://user-images.githubusercontent.com/40715953/78168251-cef13300-7479-11ea-8163-521797930100.png)

**Comment by Ilanevazno** [comment]
Так оно установлено, я умудрился с ним допустить очепятку -_-
Поправил

**Comment by Ilanevazno** [comment]
Я нашёл возможность проверить по всем файлам проекта, но это не самая лучшая идея. Пришлось самостоятельно проходиться, поискал по всем файлам, поправил все найденные опечатки.

**Comment by imin314** [comment]
В reviews.pug опечатка: `section.reviews-conatiner`

**Comment by Ilanevazno** [comment]
Это уже исправил во вермя рефакторинга.
