### ISSUE TITLE
Имя блока должно совпадать с названием файла и класса

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#12]
Это ошибка из предыдущего проекта. Посмотри на скриншоте места, отмеченные красным.
Папка arrows, миксин arrow, а класс arrow-button.
![Снимок экрана от 2020-04-02 00-42-13](https://user-images.githubusercontent.com/40715953/78169203-3bb8fd00-747b-11ea-88a6-e90b5e3901f4.png)

**Comment by imin314** [comment]
Вот еще пример неправильного нэйминга для блока button.
![Снимок экрана от 2020-04-02 01-06-46](https://user-images.githubusercontent.com/40715953/78171160-43c66c00-747e-11ea-86c9-9d36f8c677cf.png)

**Comment by Ilanevazno** [comment]
Исправил

**Comment by imin314** [comment]
![Выделение_018](https://user-images.githubusercontent.com/40715953/78397941-5ecee280-761c-11ea-826b-82df4e804981.png)

**Comment by Ilanevazno** [comment]
А что здесь не так?
Из параметров нельзя менять headerClassName? Он используется для того, чтобы можно было добавить тему

**Comment by Ilanevazno** [comment]
Исправил

**Comment by imin314** [comment]
В scss надо сделать так, чтобы имя блока не повторялось в других селекторах:

![Выделение_066](https://user-images.githubusercontent.com/40715953/78985432-ff5c5f80-7b52-11ea-8b14-cf1a286b7e63.png)

**Comment by Ilanevazno** [comment]
Исправил по всему проекту (за исключением, конечно же, календаря)

**Comment by imin314** [comment]
К папкам это правило тоже относится:
![Выделение_022](https://user-images.githubusercontent.com/40715953/79146520-bcb5b400-7dec-11ea-9451-c3c2b15791f5.png)

**Comment by Ilanevazno** [comment]
fixed

**Comment by imin314** [comment]
![Выделение_057](https://user-images.githubusercontent.com/40715953/79857864-9c8f8180-83f8-11ea-8480-45f092fe1e7d.png)

**Comment by Ilanevazno** [comment]
Исправил.
