### ISSUE TITLE
Не используй миксы

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#13]
С помощью параметра hookClassName ты даешь возможность снаружи добавить произвольный класс к твоему блоку (нижняя фиолетовая линия). Почему это плохо, я уже писала. Можешь еще раз прочитать тут: [5 пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md)

![Снимок экрана от 2020-04-02 00-42-13](https://user-images.githubusercontent.com/40715953/78169349-6f942280-747b-11ea-9481-3814bca8c49a.png)

**Comment by Ilanevazno** [comment]
Исправил в ишью №12
