### ISSUE TITLE
Имена переменных и модификаторов

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#14]
Название свойства isDisable неправильно с точки зрения грамматики английского языка.
В такой форме нужно использовать isDisabled.

Модификатор arrow-button_direction_arrow-left избыточное - постфикса direction_left было бы достаточно.
![Снимок экрана от 2020-04-02 00-42-13](https://user-images.githubusercontent.com/40715953/78169938-635c9500-747c-11ea-800b-e76a9a3e2f1a.png)

**Comment by imin314** [comment]
В имени `size_hight` опечатка в слове hight. Ты вероятно имел в виду high. Но мне кажется, что прилагательное высокий и низкий не очень сочетаются с ключом "размер". Может, лучше использовать small, large, так как кнопки отличаются друг от друга не только высотой, но и шириной, и размером шрифта.

![Снимок экрана от 2020-04-02 01-13-36](https://user-images.githubusercontent.com/40715953/78171802-3493ee00-747f-11ea-925d-a56e06973824.png)

**Comment by Ilanevazno** [comment]
По поводу hight, high, small, large прямо в точку 😸 
Исправил в ишью №12

**Comment by imin314** [comment]
Глагол catch - неправильный. Правильная форма - caught:
![Выделение_017](https://user-images.githubusercontent.com/40715953/79144808-c8ec4200-7de9-11ea-9d4f-1ed8d42506d3.png)

**Comment by Ilanevazno** [comment]
![image](https://user-images.githubusercontent.com/46503497/79259360-43be6700-7e95-11ea-9618-1e458f83e1d1.png)

![image](https://user-images.githubusercontent.com/46503497/79259392-5042bf80-7e95-11ea-9be7-165f7e5d3e24.png)

Точно?

**Comment by Ilanevazno** [comment]
Поправил

**Comment by imin314** [comment]
Перепроверь глобально.

**Comment by imin314** [comment]
Имя метода bootstrap() вводит в заблуждение из-за ассоциации с одноименной библиотекой. 
![Выделение_069](https://user-images.githubusercontent.com/40715953/79861386-884e8300-83fe-11ea-9211-46c2ad1ebc6e.png)

**Comment by imin314** [comment]
Правильно будет leftAngle, rightAngle.
![Выделение_075](https://user-images.githubusercontent.com/40715953/79863040-4541df00-8401-11ea-9bfd-31d12acf42de.png)

Название объекта htmlObjects не очень содержательное. Он предназначен для хранения иконок, поэтому лучше переименовать его в svgIcons.
Еще сам svg для иконок лучше минимизировать, можно использовать онлайн-сервис, например: [https://www.svgminify.com/](https://www.svgminify.com/) (но он тоже оставляешь некоторые атрибуты, которые не нужны в html svg).
Также удобно будет вынести эти иконки в переменные вне класса и значение записать с помощью шаблонной строки, поддерживающей переносы строк (можно сохранить структуру).

**Comment by Ilanevazno** [comment]
Поправил

**Comment by imin314** [comment]
Имя метода bootstrap осталось без изменений.

**Comment by Ilanevazno** [comment]
Исправил

**Comment by imin314** [comment]
Подобные сокращения не рекомендуется использовать:
![Выделение_200](https://user-images.githubusercontent.com/40715953/80587802-67f77780-8a41-11ea-9b1b-ecdaa9092f13.png)

**Comment by Ilanevazno** [comment]
Поправил данные сокращения, изменил название openMM

**Comment by imin314** [comment]
По тем ишьюзам всё ок. И несколько новых:

1) С $ надо именовать только переменные, в которых хранятся объекты jQuery: 
![Выделение_254](https://user-images.githubusercontent.com/40715953/80853232-30631800-8c59-11ea-82c9-f9dcc57927a9.png)

2) Правильно targetIsShown, а еще лучше isTargetShown (обычно просто is в начале ставится), а для targetNotItemList ошибка в том, что в названии надо использовать утвердительную форму ([см. пункт 6](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/variablesNaming.md)).
![Выделение_252](https://user-images.githubusercontent.com/40715953/80853269-a0719e00-8c59-11ea-9993-675e77977b2b.png)

**Comment by Ilanevazno** [comment]
1. поправил;
2. поправил, но по поводу targetNotItemList, я сделал targetIsNotItemList, потому что это утвердительная переменная;
3. Здесь понравился вариант булевого значения isShown, я его использовал;
4. поправил;
5. поправил в рефакторинге до появления текущего ишью.

**Comment by imin314** [comment]
2. Как же это утвердительная переменная, если в ее названии используется отрицание. Можно использовать isItemListClicked, например.

**Comment by Ilanevazno** [comment]
Требования ещё раз перечитал, ошибку понял. Заменил переменную на isItemListClicked
