### ISSUE TITLE
Использование модификаторов

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#15]
Здесь ты элементу arrow-button__inner добавляешь модификатор arrow-button_direction_arrow-left. Это неправильно, потому что модификатор элемента должен содержать в названии класс элемента. Тут ты можешь переместить модификатор на уровень блока и использовать в CSS наследование, чтобы определить стиль для левой и правой стрелок.
![Снимок экрана от 2020-04-02 00-42-13](https://user-images.githubusercontent.com/40715953/78170220-d239ee00-747c-11ea-8f2b-db005e947dc6.png)

**Comment by Ilanevazno** [comment]
Исправил в ишью №12

**Comment by Ilanevazno** [comment]
Если правильно понял, то готово :)

**Comment by Ilanevazno** [comment]
Во первых ошибка была в кривом названии - arrow-button_direction-arrow-left (правильнее было бы arrow-button_direction_left), это я поправил
Во вторых - в классе рядом с модификатором должно быть и название главного класса, а раньше его не было (arrow-button)

**Comment by Ilanevazno** [comment]
Поправил
