### ISSUE TITLE
Путаница в классах. Элементы не по БЭМ

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#18]
У тебя сейчас есть глобальная проблема, что к одному элементу привязано несколько классов:
![Выделение_021](https://user-images.githubusercontent.com/40715953/78397375-51652880-761b-11ea-94f2-6ad6c192469b.png)

В блоке dropdown совсем запутался в классах:
![Выделение_020](https://user-images.githubusercontent.com/40715953/78397392-5924cd00-761b-11ea-8bb4-47ab111ff6e2.png)

![Выделение_023](https://user-images.githubusercontent.com/40715953/78397295-309cd300-761b-11ea-9b77-93fe9091b55e.png)

В БЭМ элементы создаются с помощью классов, выходит у тебя один элемент является сразу несколькими элементами. Надо поправить - на элементе (или блоке) могут быть только собственный класс, его модификаторы и его же класс с префиксом js-.

**Comment by Ilanevazno** [comment]
Да, получилась каша, это когда я правил нейминг блоков в зависимости от названия миксинов 🌵 . 
Поправил по всем файлам.

**Comment by imin314** [comment]
![Выделение_073](https://user-images.githubusercontent.com/40715953/78988329-d93abd80-7b5a-11ea-88de-092d7c6a2210.png)

**Comment by Ilanevazno** [comment]
Захватил пока правил #12 ишью
