### ISSUE TITLE
Слишком длинные строки в pug

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#19]
Подобные строки надо разбивать на несколько по правилам стайлгайда airbnb:
![Выделение_017](https://user-images.githubusercontent.com/40715953/78397758-fe3fa580-761b-11ea-9ec3-4aeafedb14c9.png)

**Comment by Ilanevazno** [comment]
Поправил в issue 22

**Comment by imin314** [comment]
Опечатка в слове class _(lass="donut-segment")_

И зачем нужна строка `const [] = donut;` ?
![Выделение_067](https://user-images.githubusercontent.com/40715953/78985736-b6f17180-7b53-11ea-844c-331b406c98b8.png)

**Comment by Ilanevazno** [comment]
Это старая строчка, забыл удалить. Сейчас её функцию выполняет пустой массив из аргумента donutData. 

Поправил 'lass' и убрал эту строку
