### ISSUE TITLE
Привязка label к input

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#20]
Ты видимо удалил id, но теперь label не привязан к input, потому что привязка идет не через name, а id. Нужно поместить input в label, тогда id и for не нужны.
![Выделение_019](https://user-images.githubusercontent.com/40715953/78398085-a3f31480-761c-11ea-9bc5-1257f49815e9.png)

**Comment by imin314** [comment]
![Выделение_020](https://user-images.githubusercontent.com/40715953/78398365-2aa7f180-761d-11ea-8c15-6e5db88f8c01.png)

**Comment by Ilanevazno** [comment]
Исправил в issue #22
