### ISSUE TITLE
Задание классов в pug

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#21]
Когда ты задаешь классы через атрибут class, визуально код становится тяжелее воспринимать (из-за другой подсветки). Если значение класса не вычисляется, то лучше использовать конструкцию`.className(attributes...)`. Причем, если тебе потом надо добавить вычисляемое значение класса, не нужно использовать конкатенацию. Просто в атрибуте привычным способом указываешь `class=someModifier` и он добавится в дополнение к твоему основному классу.
![Выделение_021](https://user-images.githubusercontent.com/40715953/78398503-604cda80-761d-11ea-9ef4-2b74fc9b8af4.png)

**Comment by Ilanevazno** [comment]
Исправил во всех файлах
