### ISSUE TITLE
SVG-иконки

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#22]
Иконки социальных сетей лучше вынести в отдельный блок. В миксине не придется повторять одинаковый код svg, только рендерить содержимое `<path>` в зависимости от типа иконки. Кстати, пустой тэг `<defs>` и дублирующий `<g>` можно удалить.
![Выделение_022](https://user-images.githubusercontent.com/40715953/78399026-58416a80-761e-11ea-86f0-3781f8249341.png)

**Comment by Ilanevazno** [comment]
Исправил
