### ISSUE TITLE
Сортировка стилей

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#24]
По стандартам стили должны быть отсортированы в порядке расположения соответствующих элементов на странице:
![Выделение_069](https://user-images.githubusercontent.com/40715953/78987103-3af92880-7b57-11ea-8943-6c4ddd3aaf2a.png)

**Comment by Ilanevazno** [comment]
Готово, прошёлся по всему проекту с данным ишью.

**Comment by imin314** [comment]
Здесь псевдоклассы оторваны от элемента, к которому они относятся, и разделяют стили .inner.
![Выделение_025](https://user-images.githubusercontent.com/40715953/79147204-c68be700-7ded-11ea-834a-10851b723f94.png)

**Comment by Ilanevazno** [comment]
Теперь буду знать. Исправил)

**Comment by imin314** [comment]
Теперь стрелка при hover не видна.
![Выделение_060](https://user-images.githubusercontent.com/40715953/79858091-09a31700-83f9-11ea-977f-ed69fd614110.png)
![Выделение_061](https://user-images.githubusercontent.com/40715953/79858097-0a3bad80-83f9-11ea-9138-42c1b27c2d95.png)

**Comment by Ilanevazno** [comment]
arrow buttons поправил
