### ISSUE TITLE
Глобальные библиотеки

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#25]
По [стандартам (1 пункт)](https://github.com/fullstack-development/front-end-best-practices/blob/master/Initiation.md) все библиотеки, которые можно установить через npm, не должны быть глобальными:
![Выделение_070](https://user-images.githubusercontent.com/40715953/78987414-22d5d900-7b58-11ea-929a-46cbb9f92792.png)

**Comment by Ilanevazno** [comment]
Это jRange, я поискал, и не нашёл его на NPM - https://nitinhayaran.github.io/jRange/demo/

А по ишью, удалил jQuery и canvas2d (первый уже имеется глобально, второй не используется)

**Comment by imin314** [comment]
Первый результат в гугле на запрос [jRange npm](https://www.npmjs.com/package/jquery-range)

**Comment by Ilanevazno** [comment]
Тогда сорян, у  меня при гугле jRange npm отсутствует такой результат:

![image](https://user-images.githubusercontent.com/46503497/79148330-faefab00-7dcd-11ea-8c47-7dbbb000b514.png)

**Comment by Ilanevazno** [comment]
Вероятнее всего, NPM версия виджета, и скачиваемая, не совпадают. Потому что при попытке использовать NPM версию, у меня поехало абсолютно всё, начиняа со стилей, заканчивало функционалом. Поэтому я решил оставить библиотеку в папке vendor.

**Comment by imin314** [comment]
Тогда по стандартам нужно в package.json прописать пути до локальных модулей:
_Если используются дополнительные модули, то в package.json должны быть прописаны пути до локальных модулей, которые вы установили._

**Comment by Ilanevazno** [comment]
поправил
