### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#26]
Надо добавить тип woff2 [по стандартам (пункт 2)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/fonts.md).
![Выделение_071](https://user-images.githubusercontent.com/40715953/78987606-b7d8d200-7b58-11ea-9d33-e9f04b899704.png)

**Comment by Ilanevazno** [comment]
Добавил и импортировал woff2 файлы

**Comment by imin314** [comment]
По стандартам ([пункт 4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/fonts.md)) разные начертания одного и того же шрифта подключайте под одним именем, но для разных font-weight и font-style:
```
@font-face{
    font-family: 'Lato black';
    src: url('../assets/fonts/lato-black.woff2') format('woff2'),
    url('../assets/fonts/lato-black.woff') format('woff'),
    url('../assets/fonts/lato-black.ttf') format('ttf'),
    url('../assets/fonts/lato-black.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}

@font-face{
    font-family: 'Lato Light';
    src: url('../assets/fonts/lato-light.woff2') format('woff2'),
    url('../assets/fonts/lato-light.woff') format('woff'),
    url('../assets/fonts/lato-light.ttf') format('ttf'),
    url('../assets/fonts/lato-light.svg') format('svg');
    font-weight: light;
    font-style: normal;
}

@font-face{
    font-family: 'Lato Bold';
    src: url('../assets/fonts/lato-bold.woff2') format('woff2'),
    url('../assets/fonts/lato-bold.woff') format('woff'),
    url('../assets/fonts/lato-bold.ttf') format('ttf'),
    url('../assets/fonts/lato-bold.svg') format('svg');
    font-weight: light;
    font-style: normal;
}

@font-face{
    font-family: 'Lato Regular';
    src: url('../assets/fonts/lato-regular.woff2') format('woff2'),
    url('../assets/fonts/lato-regular.woff') format('woff'),
    url('../assets/fonts/lato-regular.ttf') format('ttf'),
    url('../assets/fonts/lato-regular.svg') format('svg');
    font-weight: light;
    font-style: normal;
}
```

**Comment by Ilanevazno** [comment]
Уфф... в общем, теперь у всех подключенных шрифтов одинаковый font-family и разные font-weight и font-style. В общем scss файле сделал font-family: 'Lato', Arial, sans-serif; и прошёлся по всему документу, убрав везде font-family, в основном поставил каждому блоку соответствующий font-weight.

**Comment by imin314** [comment]
В font-style и font-weight для нескольких шрифтов невалидные значения:
![Выделение_298](https://user-images.githubusercontent.com/40715953/81063936-ef8e2c00-8f02-11ea-8d0d-0e8b89858241.png)

**Comment by Ilanevazno** [comment]
Поправил

**Comment by Ilanevazno** [comment]
commit https://github.com/Ilanevazno/UI-KIT/commit/2ba112a8fcf926b6e2e44377641a97afe313fd10
