### ISSUE TITLE
Кнопки, вложенные в ссылки

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#27]
Если тебе нужно по клику на кнопке переходить на другую страницу, надо предусмотреть в миксине возможность выбора тэга `<a>` или `<button>`. Также, для локальных страниц атрибуты target и rel не нужны.
![Выделение_072](https://user-images.githubusercontent.com/40715953/78988119-35e9a880-7b5a-11ea-97df-ce8f462cfb3c.png)

**Comment by Ilanevazno** [comment]
Внёс данную фичу, и исправил соответствующие моменты в вёрстке (там где были обёртки с <a>)

**Comment by imin314** [comment]
Параметры target и rel ты ищешь в объекте с параметрами миксина, хотя логика подразумевает, что их значение рассчитывается на основе свойства local. Надо вынести их из деструктуризации.

![Выделение_003](https://user-images.githubusercontent.com/40715953/79138693-24fd9900-7ddf-11ea-8f5f-ee8c1c41fe92.png)

То же самое про тег. Зачем передавать его явно, если и без `tag: 'button'`, будет получено это значение в зависимости от наличия `href`.
![Выделение_002](https://user-images.githubusercontent.com/40715953/79138906-8887c680-7ddf-11ea-9098-2a59a374275b.png)

**Comment by Ilanevazno** [comment]
Да, так логичнее. Поменял.

**Comment by imin314** [comment]
У тебя переменные объявляются без const:
![Uploading Выделение_063.png…]()
