### ISSUE TITLE
Формы

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#28]
Элементы формы должны быть вложены в форму:
![Выделение_074](https://user-images.githubusercontent.com/40715953/78988791-194e7000-7b5c-11ea-89e7-98eb9aac94f0.png)

Надо подумать, на каком уровне задать тэг `<form>`, чтобы при переиспользовании блока не появлялись вложенные формы.

**Comment by Ilanevazno** [comment]
Исправил, проверил по всему проекту
