### ISSUE TITLE
Круговые диаграммы

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#29]
1) Тег `<div>` - элемент HTML, его нельзя делать потомком `<svg>`:
![Выделение_008](https://user-images.githubusercontent.com/40715953/79142341-86c10180-7de5-11ea-8987-7918017e2295.png)

2) По макету сегменты donut-chart должны отрисовываться по часовой стрелке от позиции в 12 часах. Если в твой миксин передать другие данные, начало сместится:
![Выделение_009](https://user-images.githubusercontent.com/40715953/79143112-d6ec9380-7de6-11ea-9915-161cae7c7e5d.png)

Вот такой подход работает только, если последний сегмент будет равен 10:
![Выделение_010](https://user-images.githubusercontent.com/40715953/79143145-e7047300-7de6-11ea-83d0-2452618ae5d3.png)
![Выделение_011](https://user-images.githubusercontent.com/40715953/79143150-e8ce3680-7de6-11ea-8dce-b74c22a88410.png)

**Comment by Ilanevazno** [comment]
div убрал, transform убрал, смещение поправил )

**Comment by imin314** [comment]
Теперь у тебя лэйбл не по центру:
![Выделение_064](https://user-images.githubusercontent.com/40715953/79858976-7965d180-83fa-11ea-864f-5eea3bb4197d.png)

А почему цвета ты все-таки решил не смещать, как в макете?

**Comment by Ilanevazno** [comment]
Это обговорили, уже пофикшено.
