### ISSUE TITLE
Типы для input

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#30]
Для инпутов надо использовать соответствующие значения атрибута type.
Для паролей и полей поисковых запросов в html предусмотрены специальные значения type:
![Выделение_012](https://user-images.githubusercontent.com/40715953/79143957-529b1000-7de8-11ea-993a-7c4464e868b4.png)
![Выделение_013](https://user-images.githubusercontent.com/40715953/79143962-5464d380-7de8-11ea-96da-795758d06131.png)

Кстати, есть какая-то разумная причина, по которой значение текстового поля устанавливается не через атрибут `value`, а через `<label>`?

**Comment by Ilanevazno** [comment]
тип инпута поправил, по поводу твоего вопроса - это не значение тестового поля, это статус поиска.
