### ISSUE TITLE
Именование обработчиков событий

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#31]
По стандартам (см. пункт [3](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/functionsNaming.md)) должны именоваться как handleElementNameEventName:

![Выделение_016](https://user-images.githubusercontent.com/40715953/79144760-b3771800-7de9-11ea-9b16-646aa86bcdb5.png)

**Comment by Ilanevazno** [comment]
Готово

**Comment by imin314** [comment]
В htmlContainer сохранен не openPopupButton. 
![Выделение_070](https://user-images.githubusercontent.com/40715953/79861685-f85d0900-83fe-11ea-80a3-f4cc81e77dbb.png)

**Comment by Ilanevazno** [comment]
Да, заметил. 

Поправил.

**Comment by imin314** [comment]
startIcon было правильным названием

**Comment by Ilanevazno** [comment]
Вернул
