### ISSUE TITLE
Деструктуризация параметров миксина

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#32]
По стандартам airbnb (см. [пункт 5.1](https://github.com/airbnb/javascript#destructuring--object)) рекомендуется деструктурировать объект с параметрами функции непосредственно в круглых скобках после имени функции.
![Выделение_018](https://user-images.githubusercontent.com/40715953/79145253-88d98f00-7dea-11ea-8e23-4d29c3eab03c.png)

**Comment by Ilanevazno** [comment]
Поправил по всему проекту, там где требовалось 1-2 параметра, 3 и более - уже многовато.

**Comment by imin314** [comment]
Лучше делать одинаково по всему проекту, переноси строки по стандарту airbnb, если длина строки слишком большая. 
И опции миксинов лучше везде передавать через объект:
![Выделение_067](https://user-images.githubusercontent.com/40715953/79860080-402e6100-83fc-11ea-95d7-ecb974dedf27.png)

**Comment by Ilanevazno** [comment]
Понял, хорошо.
Поправил.

**Comment by imin314** [comment]
Миксин принимает массив, а по умолчанию стоит {}:
![Выделение_134](https://user-images.githubusercontent.com/40715953/80299866-02e21e80-87c2-11ea-8050-efa87c50d1e7.png)

**Comment by Ilanevazno** [comment]
изменил
