### ISSUE TITLE
Фиксированные ширина и высота

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#33]
Пока что пример ненужного задания высоты:
![Выделение_019](https://user-images.githubusercontent.com/40715953/79145666-3f3d7400-7deb-11ea-958d-c1705378b83d.png)

Ты используешь height для управления высотой флекс-элементов в вертикальном флексбоксе, хотя в данном случае применение флексбокса кажется излишним: заголовок и контейнер для кнопок и так будут располагаться друг под другом, а выравнивания по центру можно добиться одним свойством text-align.
![Выделение_020](https://user-images.githubusercontent.com/40715953/79145877-92172b80-7deb-11ea-9e62-d65bd59a8661.png)

И лучше между кнопками добавить немного пространства. В стандартах даже есть [пункт 10 про "лепку"](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/generalRequirements.md).

**Comment by Ilanevazno** [comment]
Убрал фиксированную ширину в панеле аккаунта, и прошёл по всем компонентам, заметил ещё одну в user-profile (тоже поправил)

**Comment by imin314** [comment]
Правка была о том, что здесь можно обойтись без вертикального флексбокса и высоты (height, min-height).

**Comment by Ilanevazno** [comment]
Можно, но всё таки мне удобнее через флексбокс.

**Comment by imin314** [comment]
А можешь объяснить, в чем проявляется удобство?:) Вертикальный порядок у p и div был бы по умолчанию, выравнивание по центру делается с помощью text-align: center.
Свойство height: max-content совершенно ни на что не влияет.
![Выделение_130](https://user-images.githubusercontent.com/40715953/80299463-bea14f00-87be-11ea-89bf-53e9b8f47310.png)

Управление отступом между заголовком и кнопками происходит через высоту. Вместо этого нужно использовать margin.
![Выделение_133](https://user-images.githubusercontent.com/40715953/80299482-dd074a80-87be-11ea-83d9-cd0a81031f7c.png)

Чтобы установить горизонтальный отступ между кнопками, ты переопределяешь box-sizing на content-box, чтобы ширина оставалась шириной контента, а padding не входил в это значение. Это очень неочевидное поведение, которого легко избежать, если использовать контейнеры-обертки и управлять отступами между кнопками в них.
![Выделение_132](https://user-images.githubusercontent.com/40715953/80299511-1a6bd800-87bf-11ea-8ba1-76b702cc1ca5.png)

**Comment by Ilanevazno** [comment]
сменил вёрстку.
