### ISSUE TITLE
Мелкие замечания по scss

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#34]
Если устанавливаешь outline: none, нужно предусмотреть свои стили. Иначе при навигации табом, пользователь не увидит, что фокус находится на этом элементе:
![Выделение_023](https://user-images.githubusercontent.com/40715953/79146853-38176580-7ded-11ea-8c20-24a600737ce9.png)

**Comment by imin314** [comment]
Ненужные свойства надо удалять:
![Выделение_027](https://user-images.githubusercontent.com/40715953/79147754-a4df2f80-7dee-11ea-85ab-ba8fd5952ace.png)

**Comment by Ilanevazno** [comment]
Готово

**Comment by imin314** [comment]
Элементам, поддерживающим взаимодействие с помощью мыши, надо добавлять cursor: pointer.
![Выделение_076](https://user-images.githubusercontent.com/40715953/79863700-635c0f00-8402-11ea-9fe5-dd87366c1c8d.png)

**Comment by Ilanevazno** [comment]
Пробежался по всем компонентам, только у этих стрелок не было cursor:pointer, добавил

**Comment by imin314** [comment]
В календаре еще есть кнопка "TODAY".

**Comment by Ilanevazno** [comment]
Готово)

**Comment by imin314** [comment]
1) stages.scss
* Не используются rem.
* В миксине remain-steps для `::before` задаются общие свойства, которые уже заданы в `&-item::before`. Свойство из `::after` лучше перенести непосредственно в селектор `~ .stages__multi-steps-item`.
* В `&.is-active::before` тоже все свойства, уже назначенные `&-item::before`.
* Попробуй избавиться от многоуровневой вложенности. Для этого, например, вместо `border { }` можно использовать border и border-radius. Также можно поместить селекторы для ` &__multi-steps-item` и `~ .stages__multi-steps-item` уровнем выше.

```
%remain-steps {
  &:before {
    content: counter(stepNum);
    font-family: inherit;
    font-weight: 700;
  }

  &:after {
    background-color: $gray-template;
  }
}
```

**Comment by Ilanevazno** [comment]
1. Насколько я знаю, по стандартам rem'ы не обязательно использовать везде, но всё же согласен, они явно превосходят пиксели;
2. Убрал миксин, перемести соответствующие свойства;
3. Поправил;
4. По возможности понизил уровень вложенности.
