### ISSUE TITLE
Мелкие замечания по pug

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#35]
В arrow-button у тега <button> не задан атрибут type, а, значит, кнопка по умолчанию будет иметь тип 'submit'. Этот тип используется для отправки формы на сервер, но парные кнопки-стрелки вряд ли предназначены для этого. 
![Выделение_026](https://user-images.githubusercontent.com/40715953/79148259-66964000-7def-11ea-8e29-87b924855351.png)

Зачем нужно разделять название файла от пути к нему? Переменная avatarName нигде, кроме как, пути не используется.
![Выделение_028](https://user-images.githubusercontent.com/40715953/79148611-f340fe00-7def-11ea-8322-f0909f277b30.png)

**Comment by Ilanevazno** [comment]
Поправил подключения, поправил arrow button
Случайно запушил с ишью #34

**Comment by imin314** [comment]
Если в миксин передаются параметры по умолчанию, их не нужно явно указывать. Также можно для текста вместо дефолтного значения text указать 'Button', тогда не придется и его передавать в миксин.
![Выделение_140](https://user-images.githubusercontent.com/40715953/80300468-4d19ce80-87c7-11ea-9850-59e8f10216f2.png)

**Comment by Ilanevazno** [comment]
Поправил по всем файлам

**Comment by imin314** [comment]
Не хватает отступов:
![Выделение_208](https://user-images.githubusercontent.com/40715953/80591414-db9c8300-8a47-11ea-8a61-ee1d94c84767.png)

**Comment by Ilanevazno** [comment]
Исправил.

**Comment by imin314** [comment]
1. Надо добавить еще отступ перед закрывающей фигурной скобкой для объекта с параметрами (14 строка).

**Comment by Ilanevazno** [comment]
Надо добавить еще отступ перед закрывающей фигурной скобкой для объекта с параметрами (14 строка). 
Не совсем понял, возможно я уже это поправил во время рефакторинга, но не нашёл где нужно добавлять пробел. 
![image](https://user-images.githubusercontent.com/46503497/80892290-88d5fc00-8cd1-11ea-8eb1-7591c52bc8b4.png)

2. Уже правлено во время рефакторинга
3. Заменил var на let, и не совсем понял, зачем в данном виджете подгружать текст через html, ведь тогда получится странный и бесполезный список, но стандарты есть стандарты ))
4. лишнюю запятую убрал
5. Поправил svg
6. Поправил вложенность
7.  Отрефакторил контакты, циклом выглядит правильнее.)
4.

**Comment by imin314** [comment]
7. Здесь не нужно деструктурировать объект contact, т. к. в миксин contact-section ты передаешь тот же объект.
После миксина зачем-то `= contact`.
![Выделение_296](https://user-images.githubusercontent.com/40715953/81062768-c4a2d880-8f00-11ea-9ca0-33c00331e3b6.png)

**Comment by Ilanevazno** [comment]
1. добавил отступ;
2. поправил исправил 'counter +1' и дублирование кода в if/else
3. поправил, так выглядит намного лучше
