### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#36]
Позиционирование fixed, absolute, sticky тоже относится к внешнему позиционированию блока, которое нужно переносить в элементы-обертки. Иначе, чтобы изменить положение блока на какой-нибудь одной странице, придется создавать дополнительные модификаторы, чтобы ничего не сломать на других страницах:
![Выделение_137](https://user-images.githubusercontent.com/40715953/80300244-278bc580-87c5-11ea-8e41-a9e7cb19062b.png)

**Comment by Ilanevazno** [comment]
Согласен, поправил.

**Comment by imin314** [comment]
В модификаторах предлоги - это не ключевые слова, их надо писать через дефис:
![Выделение_205](https://user-images.githubusercontent.com/40715953/80590902-e73b7a00-8a46-11ea-9c8a-edb4e11f4574.png)

**Comment by Ilanevazno** [comment]
Согласен. эти именования могут запутать, поэтому я их переименовал.
