### ISSUE TITLE
Мелкие замечания по js

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#37]
1. Два раза создается jQuery-объект. В первом случае для элемента html, во втором - для jQuery-объекта.
![Выделение_138](https://user-images.githubusercontent.com/40715953/80300357-30c96200-87c6-11ea-8161-c026fc92caed.png)
![Выделение_139](https://user-images.githubusercontent.com/40715953/80300358-3161f880-87c6-11ea-827c-1e3617fcea2e.png)

2. Необязательно в конструкторе объявлять все свойства класса. Эта строка лишняя:
![Выделение_142](https://user-images.githubusercontent.com/40715953/80300636-a6cec880-87c8-11ea-8df8-916484bd3b3a.png)

3. Операции с DOM нужно проводить сначала на виртуальных элементах и только после этого добавлять их в html. Здесь можно text перенести во второй аргумент конструктора jQuery-объекта.
![Выделение_143](https://user-images.githubusercontent.com/40715953/80300651-ca920e80-87c8-11ea-88f8-70a1ab809cd4.png)

4. Составные условия лучше упрощать с помощью дополнительных поясняющих переменных. Нужно каждое условие вынести в переменную с осмысленным названием, избавиться от стрелочной функции, а значение булевой переменной isCanClose получать напрямую. Например, `const isCanClose = isFirstConditionTrue && isSecondConditionTrue`.
![Выделение_155](https://user-images.githubusercontent.com/40715953/80301345-d207e680-87cd-11ea-981b-f27cbf04a927.png)

5. В SearchForm.js `itemList` кажется то же самое, что и `searchListOptions`. Если это так, то лучше лишний раз не выполнять поиск по DOM.
![Выделение_157](https://user-images.githubusercontent.com/40715953/80301610-3bd4c000-87cf-11ea-9de5-e2983db86a9c.png)

6. Все классы нужно инициировать в цикле, чтобы быть уверенным, что js для блока будет работать вне зависимости от того, сколько раз этот блок будет использоваться в проекте.
![Выделение_160](https://user-images.githubusercontent.com/40715953/80302117-53fa0e80-87d2-11ea-83b3-c712f0cfaaac.png)

**Comment by Ilanevazno** [comment]
Поправил.

**Comment by imin314** [comment]
Сложное условие и стрелочная функция остались:
![Выделение_202](https://user-images.githubusercontent.com/40715953/80589450-67acab80-8a44-11ea-8043-0ff0ec119a00.png)

**Comment by Ilanevazno** [comment]
Стрелочную функцию убрал (она с прошлым коммитом куда-то потерялась);
2 пункт так же исправлен;
У ripple-button изменено название, и инициализация.

**Comment by imin314** [comment]
По тем пунктам все ок. Хотя я бы в импорте RippleButton указала бы не Button, а RippleButton.

**Comment by Ilanevazno** [comment]
1. Вообще, это служебный метод был для того чтобы показать, что видео работает (в одном из ишью такая просьба была), но раз уж дело пошло, сделал data атрибут;
2. да, уже поправил во время рефакторинга;
3. метод удалил, строку удалил. :)
