### ISSUE TITLE
Файловая структура

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#38]
Все подгружаемые файлов (картинки, шрифты) должны быть названы в стиле lowe-case-hyphenated:
![Выделение_207](https://user-images.githubusercontent.com/40715953/80591275-9bd59b80-8a47-11ea-900f-5e887162e659.png)

**Comment by Ilanevazno** [comment]
Поправил.

**Comment by imin314** [comment]
А те, что были с заглавной буквы, остались в репозитории:
![Выделение_249](https://user-images.githubusercontent.com/40715953/80852815-b8472300-8c55-11ea-88ce-292d0db7c500.png)

**Comment by Ilanevazno** [comment]
Ох уж этот case.. удалил вручную.

**Comment by imin314** [comment]
Сейчас проект не собирается. В стилях остались заглавные буквы.

**Comment by Ilanevazno** [comment]
На Windows запускается.
Исправил.
