### ISSUE TITLE
Контекст this в обработчиках событий

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#39]
В стандартах ([пункт 12](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md)) рекомендуется вместо контекста в обработчиках событий использовать объект события:
![Выделение_216](https://user-images.githubusercontent.com/40715953/80593570-aabe4d00-8a4b-11ea-835c-a0c98c58e513.png)

**Comment by Ilanevazno** [comment]
Провёл небольшой рефакторинг ripple button компонента.
