### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#41]
1) Slider.js
Если использовать $(elem).data('attr'), то jQuery будет автоматически преобразовывать строку в нужный формат, и не придется использовать JSON.parse:
![Выделение_262](https://user-images.githubusercontent.com/40715953/80854079-73c08500-8c5f-11ea-84ad-d50dafe2916f.png)

Сохрани $(target) в переменную и оперируй с ней:
![Выделение_264](https://user-images.githubusercontent.com/40715953/80854145-f2b5bd80-8c5f-11ea-898c-3b6e2a81cac2.png)

Не хватает имени у события:
![Выделение_265](https://user-images.githubusercontent.com/40715953/80854160-06612400-8c60-11ea-9218-6e781bb0dc33.png)

**Comment by Ilanevazno** [comment]
1. Спасибо, .data - хороший метод, исправил;
2. Готово;
3. Добавил именование событию;

**Comment by imin314** [comment]
Для того чтобы привязывать this в обработчиках событий лучше использовать автоматические байндеры. Я тебе уже писала про них в другом ишью, мне кажется.
Обычно bind для обработчиков вызывается все-таки в конструкторе класса. В твоей вариации, например, не получится удалить обработчик.
Но так как в больших проектах неудобно следить за актуальностью привязанных обработчиков, да и для каждого метода приходится писать один и тот же код, то автоматическая привязка this предпочтительней.

**Comment by Ilanevazno** [comment]
Подключить автобинд в каждом компоненте.

Commit https://github.com/Ilanevazno/UI-KIT/commit/47b50b42e40f17c37002a033be11d4e179921733
