### ISSUE TITLE
Приватные методы

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#42]
1) Нужно для приватных методов добавить префикс _.
2) В классе сначала идут публичные методы, потом приватные. Например, в классе Dropdown единственный публичный метод init() в самом конце.

**Comment by Ilanevazno** [comment]
По приваткам у меня был отдельный вопрос, в конфе сказали что не надо их подписывать, поэтому не знал.
В общем, во всех файлах отметил приватные методы, публичные соответственно теперь сверху.

**Comment by Ilanevazno** [comment]
commit 
https://github.com/Ilanevazno/UI-KIT/commit/5c985c2d23947596c68613122c15182e8aa7178e
