### ISSUE TITLE
Общие недочёты 

### ISSUE THREAD

**Issue by Feinminen** [Ilanevazno/UI-KIT#44]
Тултип находится не ровно над центром бегунка.
![image](https://user-images.githubusercontent.com/44312820/85499999-da816f80-b60c-11ea-9aa3-f5e9bb84086f.png)

Имхо, не совсем логично, что при вводе неправильных данных с точки зрения валидации, вылезает подсказка с ошибкой, но не пишется 'error'.
![image](https://user-images.githubusercontent.com/44312820/85500105-11f01c00-b60d-11ea-96e1-6d81f6682402.png)

Опять же имхо, очень странно, что у декоративной 'стрелочки' разное поведение при наведении на авку и при наведении на сам контейнер с описанием. 
![arrow](https://user-images.githubusercontent.com/44312820/85500272-66939700-b60d-11ea-903b-7087dc2bb6a3.gif)

Последняя опция дропдауна гораздо шире чем остальные, также при наведении пропадает border-radius.
![dropdown](https://user-images.githubusercontent.com/44312820/85500709-3ef0fe80-b60e-11ea-8fc4-2f36ee0a843b.gif)

Если у календаря есть возможность выбрать две даты - то это должен быть каким-то образом выделенный интервал, чтобы собственно понятно было, что это интервал) 
![image](https://user-images.githubusercontent.com/44312820/85501070-d5252480-b60e-11ea-86ee-95999043e091.png)
Можно вот так ~
![image](https://user-images.githubusercontent.com/44312820/85501477-a5c2e780-b60f-11ea-88ca-794ed40419b5.png)
А можно просто сделать так, чтобы выибралась только одна дата.
Также не совсем удобно с точки зрения UX, что для того чтобы выбрать текущую дату - нужно кликунуть именно на саму надпись TODAY, хотя можно было бы весь 'блок' сделать кнопкой, чтобы не приходилось аимить :)

**Comment by Ilanevazno** [comment]
1. Поправил;
2. Поправил;
3. Поправил;
4. Подрефакторил логику выбора дат.))

**Comment by Feinminen** [comment]
Всё ок, но сейчас логика календаря вообще странная стала. Слишком много нюансов появилось, которые с функционалом не особо вяжутся. Думаю, лучше просто оставить выбор одной конкретной даты, а не интервала.
Насчёт нюансов:
1)При клике на TODAY юзер явно ожидает, что просто выберется текущая дата и на этом всё. А сейчас сразу ещё выбор интервала идёт.
2)При выборе даты в разных месяцах нужно как-то указывать с какого по какой месяц.
3)Дата на которую юзер наводит при выборе интервала - не закрашивается до клика, можно подумать что она в интервал входить не будет.

**Comment by Feinminen** [comment]
Модификатор в кэмэл-кейсе 
![image](https://user-images.githubusercontent.com/44312820/85942927-d7f97f80-b956-11ea-8637-cb3166e3c263.png)

**Comment by Feinminen** [comment]
Зачем тут headerClassName как переменная?
![image](https://user-images.githubusercontent.com/44312820/85942995-49393280-b957-11ea-8daa-a8d3450ea565.png)

**Comment by Ilanevazno** [comment]
1. Просто сделал выбор одной даты.)
2. Поправил.
3. Раньше использовался, это я убрал.

**Comment by Feinminen** [comment]
Ещё небольшой баг обнаружил, сейчас на главной, если выбрать какой-то опшн дропдауна, то он больше не открывается на кнопку-стрелочку.
![dropdownn](https://user-images.githubusercontent.com/44312820/86511383-c581b900-be22-11ea-823f-bcbc0baae0b2.gif)

**Comment by Feinminen** [comment]
Тут элемент - прилагательное. Должно быть inner-[smth].
Пысы, я знаю что inner может переводиться как 'внутренняя часть', но я ни разу не видел употребления inner в таком значении. В ситуациях когда слово явно более популярно именно как прилагательное - лучше не использовать его как существительное, потому-что без контекста может быть не совсем понятно что именно имелось ввиду.
![image](https://user-images.githubusercontent.com/44312820/86511454-9fa8e400-be23-11ea-93ab-b2b866cdf1e3.png)

**Comment by Feinminen** [comment]
Опять же совсем незначительное замечание, но приписка 'container' для айтемов в подобный случаях(при более сложной вложенности возможно ок) - просто лишнее слово:
1) Во-первых, это по прежнему айтемы именно buttons/arrows-section, а не контейнера/враппера.
2) Во-вторых, приписка 'container' - не даёт никакой дополнительной смысловой нагрузки.
![image](https://user-images.githubusercontent.com/44312820/86511622-14c8e900-be25-11ea-930d-98a64e104fb4.png)
![image](https://user-images.githubusercontent.com/44312820/86511719-ee577d80-be25-11ea-80ce-1fc467cc0354.png)

Обычно подобные приписки используется только в том случае, если без приписки этот элемент уже есть. Т.е. допустим, у тебя есть элемент buttons-section, и этот элемент во что-то обернут, тогда прийдётся уже юзать buttons-section-wrapper/container. А если бы у тебя buttons-section был миксином(как сейчас и есть в проекте), и ты бы использовал его внутри какого-то другого блока, то у тебя бы просто элемент обертка назывался просто smth_buttons, но не smth_buttons-wrapper.
![image](https://user-images.githubusercontent.com/44312820/86511856-290de580-be27-11ea-956b-994fd1e5bd17.png)
Собственно так и есть :)

**Comment by Ilanevazno** [comment]
1. На главной не дропдаун, а поиск, он и не должен открываться на кнопку)
2. Я знал что inner - внутренняя часть :D
3. Убрал избыточное слово у айтемов

**Comment by Feinminen** [comment]
> 1. На главной не дропдаун, а поиск, он и не должен открываться на кнопку)

Просто после первого 'запроса' там иконка поиска сменяется на иконку открытия дропдауна, это очень путает)
Причем у тебя явно по вьюхе понятно, что это кнопка и она должна что-то делать, ибо на ней курсор - поинтер и ховер есть вдобавок.
Там же подобие того, что после поиска - можно глянуть его историю, но зачем тогда смена иконки поиска собстно?
У тебя же сейчас совмещен дропдаун и поиск, по факту.

**Comment by Ilanevazno** [comment]
Не, я хотел чтобы это был поиск как в гугле, это не история поиска, а все возможные варианты (ну как в гугле), а кнопка это не иконка дропдауна, а галочка, которая оповещает о том, что нужный элемент был найден ))
