### ISSUE TITLE
Дизайн и поведение компонентов ui-kit

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#7]
Для карты довольно странно продумано поведение при нажатии на левую иконку. Чтобы обнаружить местоположение, нужно ввести долготу и ширину адреса. Не очень user-friendly решение. Можно находить местоположение пользователя при нажатии на эту кнопку, а при нажатии на правую иконку возвращать карту в исходное положение.
![Выделение_011](https://user-images.githubusercontent.com/40715953/77877604-68ed8b80-7280-11ea-8df5-0e780c5d7307.png)

Нижняя граница у кнопки не соответствует макету. Углы слева и справа должны быть едиными с боковыми границами кнопки.
![Выделение_012](https://user-images.githubusercontent.com/40715953/77877839-1bbde980-7281-11ea-8e64-32f4a60d6af6.png)

Значение диаграммы не отцентровано.
![Выделение_013](https://user-images.githubusercontent.com/40715953/77877980-76efdc00-7281-11ea-96cf-71f39b6d0349.png)

Анимация ведет себя странно. Мне кажется, величина сегмента должна увеличиваться с 0, а не уменьшаться со 100:
![Peek 2020-03-30 13-45](https://user-images.githubusercontent.com/40715953/77883200-ce477980-728c-11ea-8f72-a3f603865e22.gif)

Треугольник в тултипе выглядит смещенным вправо относительно числа:
![Выделение_014](https://user-images.githubusercontent.com/40715953/77878161-de0d9080-7281-11ea-986e-1aaa4832d7dc.png)

Линия слишком узкая:
![Выделение_015](https://user-images.githubusercontent.com/40715953/77878231-10b78900-7282-11ea-81b3-983a7f4d64c6.png)

Не появляются всплывающие окошки Error, Thanks. Также инпуты должны занимать всю ширину и сжиматься при появлении сообщений Error и Thanks.
![Выделение_016](https://user-images.githubusercontent.com/40715953/77878255-1dd47800-7282-11ea-995a-4468949372d9.png)

Надписи не выровнены по вертикали:
![Выделение_017](https://user-images.githubusercontent.com/40715953/77878365-55432480-7282-11ea-90bd-b3e5555aedb7.png)

Мне кажется, эта тень при фокусе слишком яркая. Я бы увеличила значение spread и прозрачность и сделала бы зазор между границей элемента и тенью не таким очевидным. Еще тень второго инпута отображается поверх первого открытого списка и не убирается при перемещении фокуса на другой элемент.
![Выделение_018](https://user-images.githubusercontent.com/40715953/77878421-7146c600-7282-11ea-86dd-e9de7d359fe1.png)

Когда двигаешься табом по списку в search, почему-то фокус перепрыгивает 3-й элемент списка.
![Выделение_019](https://user-images.githubusercontent.com/40715953/77878658-00ec7480-7283-11ea-9562-a273ae0fc050.png)

В раскрывающемся списке иконка повернута криво:
![Выделение_022](https://user-images.githubusercontent.com/40715953/77878942-ab649780-7283-11ea-9dc2-326e592a65da.png)

**Comment by Ilanevazno** [comment]
Прошёлся по всем пунктам, исправил.

**Comment by imin314** [comment]
Кнопку не полностью поправил. Нужно, чтобы в зажатом состоянии не было рамки.

Диаграммы перепутаны местами.
![Выделение_024](https://user-images.githubusercontent.com/40715953/78164434-f0e7b700-7473-11ea-9653-987bd3c04ade.png)

А что со всплывающими окошками для формы? У меня они по-прежнему не появляются.
Цвет текста в инпутах по макету не черный.

Зачем ты поворачиваешь иконку именно на 39 градусов?
![Выделение_025](https://user-images.githubusercontent.com/40715953/78164896-b599b800-7474-11ea-9861-c0ff70b7fd4c.png)

**Comment by Ilanevazno** [comment]
Поправил, только про чёрный текст в инпутах не понял, не вижу нигде чёрного текста)

**Comment by Ilanevazno** [comment]
Увидел, поправил
