### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#8]
В пайчарте перепутаны цвета:
![Выделение_001](https://user-images.githubusercontent.com/40715953/77879782-60e41a80-7285-11ea-9c92-be412de23a89.png)

Про нижнюю границу не всё написала в другой ишью. Цвет границы отличается от макета, на макете используется цвет темнее.
![Выделение_002](https://user-images.githubusercontent.com/40715953/77879954-cafcbf80-7285-11ea-8858-e9232835579b.png)

Цвет заголовков и основного текста по макету не черный:
![Выделение_003](https://user-images.githubusercontent.com/40715953/77880000-e10a8000-7285-11ea-837f-03c07acd85e7.png)

Левая стрелка не выровнена:
![Выделение_004](https://user-images.githubusercontent.com/40715953/77880278-7d348700-7286-11ea-9b33-1bc8291811d7.png)

На этой странице надо использовать фото с макета:
![Выделение_005](https://user-images.githubusercontent.com/40715953/77880323-99d0bf00-7286-11ea-9c87-04c7d62b5696.png)

Границы карты должны быть скругленными:
![Выделение_007](https://user-images.githubusercontent.com/40715953/77880671-5fb3ed00-7287-11ea-99dc-9ef4a40fae08.png)

Фон календаря другого цвета:
![Выделение_008](https://user-images.githubusercontent.com/40715953/77880763-9853c680-7287-11ea-8234-2e2a0cc58dc6.png)

В textarea другой плейсхолдер:
![Выделение_009](https://user-images.githubusercontent.com/40715953/77880917-eff23200-7287-11ea-8e17-a6bc7aea6dff.png)

Проверь соответствие цветов в мессенджере, используй фото, текст исходящего сообщения и кнопки и стиль имени как в макете. Еще у входящего сообщения нет треугольника сверху.
![Выделение_010](https://user-images.githubusercontent.com/40715953/77880941-ff717b00-7287-11ea-82f1-8f820d80fc2f.png)

Видео: добавь скругленные углы и стоп-кадр, который будет отображаться по умолчанию, а то так непонятно, оно работает или нет. Еще можно сделать отступ снизу побольше, чтобы футер не был вплотную.
![Выделение_011](https://user-images.githubusercontent.com/40715953/77881166-90485680-7288-11ea-912d-9ac731a23d9a.png)

**Comment by imin314** [comment]
Сверху тоже можно сделать отступ побольше:
![Выделение_012](https://user-images.githubusercontent.com/40715953/77881437-34320200-7289-11ea-95b6-01817bb4f6d4.png)

**Comment by imin314** [comment]
Нужно еще пару моментов поправить:
В активном состоянии текста кнопки не видно:
![Peek 2020-04-02 00-04](https://user-images.githubusercontent.com/40715953/78165745-0067ff80-7476-11ea-9076-a46b83471f05.gif)

Число в хэдере должно меняться при выборе даты.
![Peek 2020-04-02 00-06](https://user-images.githubusercontent.com/40715953/78165754-01992c80-7476-11ea-9b04-61cef63fe9da.gif)

**Comment by Ilanevazno** [comment]
Кнопку поправил.
По поводу выбора даты, я уточнил, мой текущий плагин не позволяет такой роскоши...
Поэтому вот решил уточнить, насколько это важно, и стоит ли доделывать костыль для календаря?

**Comment by Ilanevazno** [comment]
А можно этот ишью тогда закрыть?

**Comment by imin314** [comment]
Padding в` <textarea> `не совпадает с верхними инпутами:
![Выделение_014](https://user-images.githubusercontent.com/40715953/79144211-c9380d80-7de8-11ea-9a26-5dbff8ae5e7d.png)

**Comment by Ilanevazno** [comment]
fixed

**Comment by imin314** [comment]
В календаре надо поправить отступы для числа:
![Выделение_073](https://user-images.githubusercontent.com/40715953/79862961-22172f80-8401-11ea-9f83-2be2f0afe3d2.png)

**Comment by Ilanevazno** [comment]
Поправил
