### ISSUE TITLE
Отзывчивость

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/UI-KIT#9]
Проверь положение треугольника для бегунка при изменении размера окна:
![Выделение_026](https://user-images.githubusercontent.com/40715953/78167743-24791000-7479-11ea-8121-6ed9419775ef.png)

На маленьком экране изображение не полностью покрывает элемент:
![Выделение_027](https://user-images.githubusercontent.com/40715953/78167745-25aa3d00-7479-11ea-90e6-2ead61ec763d.png)

**Comment by Ilanevazno** [comment]
Поправил

**Comment by Ilanevazno** [comment]
Поправил, в виджете ширина указывается при инициализации, и в коде была проверка на ширину браузера.
Сейчас я заменил так, чтобы он подстраивался под минимальное разрешение
